### ISSUE TITLE
Did someone run selenium script in google-chrome docker? It will stuck at webdriver.Chrome

### ISSUE THREAD

**Issue by nonths** [m1k1o/neko#405]
When I run selenium script at the google-chrome docker, it will stuck at webdriver.Chrome, about five minutes, and then, it will timeout with the following error:
Traceback (most recent call last):
  File "/home/neko/fb.py", line 54, in <module>
    driver = webdriver.Chrome(options=options, service=service)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=125.0.6422.112)
Stacktrace:
#0 0x564d60ae5e8a <unknown>
#1 0x564d607cf45c <unknown>

The logs of chromedriver is as following:
[253870:253891:0715/074440.079957:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

**Comment by nonths** [comment]
BTW, if we add chrome_options.add_argument('--headless'), it seems normal, but with UI, it will not work normally

**Comment by nonths** [comment]
The issue is caused by the configuration in the policies.json. After remove the file from the container, the issue is fixed
